#low
CIRCLE_DEFINITION = 1
THALES_THEOREM = 2
INSCRIBED_ANGLE_THEOREM = 3
PARALLEL_LINES_THEOREM = 4
TRIANGLE_ANGLESUM_THEOREM = 5
ISOSCELES_TRIANGLE_THEOREM_SIDE = 6
ISOSCELES_TRIANGLE_THEOREM_ANGLE = 7
EQUILATERAL_TRIANGLE_THEOREM = 8
PYTHAGORAS_THEOREM = 9
TRIANGLE_CENTER_OF_GRAVITY_THEOREM = 10
CONGRUENT_TRIANGLES_PROVING_THEOREM = 11
CONGRUENT_TRIANGLES_THEOREM = 12
LAW_OF_SINES = 13
# high
TANGENT_SECANT_THEOREM = 14
CHORD_THEOREM = 15
ANGLE_BISECTOR_THEOREM = 16
SIMILAR_TRIANGLE_PROVING_THEOREM = 17
SIMILAR_TRIANGLE_THEOREM = 18
SIMILAR_POLYGON_THEOREM = 19
MEDIAN_LINE_THEOREM = 20
AREA_EQUATION_THEOREM = 21
POLYGON_ANGLESUM_THEOREM = 22
LAW_OF_COSINES = 23

PARALLELOGRAM_PROPERTY = 24
RHOMBUS_PROPERTY = 25
RECTANGLE_PROPERTY = 26
SQUARE_PROPERTY = 27 
TRAPEZOID_PROPERTY = 28




ArcLengthFormula = 999
CircleAreaFormula = 998
TriangleAreaFormula = 997
QuadrilateralAreaFormula = 996
AuxiliaryLineFormula = 995